import { SimplifiedDemon } from "./types";

export const veryOldDemons: SimplifiedDemon[] = [
    { position: 1, name: "", video: null, creator: "", link: "" },
    { position: 2, name: "Tartarus", video: "9YYQBbrsV5Y", creator: "Dolphy", link: "https://pointercrate.com/demonlist/1" },
    { position: 3, name: "Zodiac", video: "HCQK_y8JutU", creator: "xander556", link: "https://pointercrate.com/demonlist/2" },
    { position: 4, name: "Kenos", video: "Bs1kVySdUtI", creator: "npesta", link: "https://pointercrate.com/demonlist/3" },
    { position: 5, name: "Cognition", video: "ih6Z1z0E5D4", creator: "Endlevel", link: "https://pointercrate.com/demonlist/4" },
    { position: 6, name: "Crimson Planet", video: "euMInLjyG6k", creator: "TrueOmega", link: "https://pointercrate.com/demonlist/5" },
    { position: 7, name: "Renevant", video: "2Y8kBw8YxO8", creator: "nikroplays", link: "https://pointercrate.com/demonlist/6" },
    { position: 8, name: "Bloodlust", video: "5SzKetF2btw", creator: "knobbelboy", link: "https://pointercrate.com/demonlist/7" },
    { position: 9, name: "Calculator Core", video: "Q3ambJFmbH4", creator: "Walroose", link: "https://pointercrate.com/demonlist/8" },
    { position: 10, name: "Lucid Nightmares", video: "G7hBE5qWx6M", creator: "CairoX", link: "https://pointercrate.com/demonlist/9" },
    { position: 11, name: "Kowareta", video: "wxWBFaZYHPM", creator: "Shiorin", link: "https://pointercrate.com/demonlist/10" },
    { position: 12, name: "Deimos", video: "FgxsNzQnF5o", creator: "Endlevel", link: "https://pointercrate.com/demonlist/11" },
    { position: 13, name: "Arctic Lights", video: "yd5cH9nvDvg", creator: "Metalface221", link: "https://pointercrate.com/demonlist/12" },
    { position: 14, name: "Visible Ray", video: "hHpaB752peM", creator: "Krampux", link: "https://pointercrate.com/demonlist/13" },
    { position: 15, name: "Ragnarok", video: "aGtXqn9HL2o", creator: "knobbelboy", link: "https://pointercrate.com/demonlist/14" },
    { position: 16, name: "The Yandere", video: "MN6Dra6yAys", creator: "Dorami", link: "https://pointercrate.com/demonlist/15" },
    { position: 17, name: "Plasma Pulse Finale", video: "xqzx9cu6XoA", creator: "Smokes", link: "https://pointercrate.com/demonlist/16" },
    { position: 18, name: "Ouroboros", video: "hLTnewDC2Hs", creator: "ViPriN", link: "https://pointercrate.com/demonlist/17" },
    { position: 19, name: "Hyper Paracosm by Endlevel", video: null, creator: "", link: "https://pointercrate.com/demonlist/18" },
    { position: 20, name: "Sigma", video: "3INdO0esQRw", creator: "MindCap", link: "https://pointercrate.com/demonlist/19" },
    { position: 21, name: "Gamma", video: "HTXRWzS2aw8", creator: "MindCap", link: "https://pointercrate.com/demonlist/20" },
    { position: 22, name: "Sonic Wave", video: "GpXTwPgweAk", creator: "Sunix", link: "https://pointercrate.com/demonlist/21" },
    { position: 23, name: "Generic Wave", video: "RL-c3PM4uhk", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/22" },
    { position: 24, name: "Spacial Rend", video: "VgiRJRBzacM", creator: "Eclipsed", link: "https://pointercrate.com/demonlist/23" },
    { position: 25, name: "Yatagarasu", video: "KgGKx0pk_wo", creator: "TrusTa", link: "https://pointercrate.com/demonlist/24" },
    { position: 26, name: "Macabre", video: "b2kGqEY8E1Q", creator: "ZephiroX", link: "https://pointercrate.com/demonlist/25" },
    { position: 27, name: "Titan Complex", video: "YuyJ5B1wejw", creator: "TCTeam", link: "https://pointercrate.com/demonlist/26" },
    { position: 28, name: "Erebus", video: "8csWDx6C2YI", creator: "BoldStep", link: "https://pointercrate.com/demonlist/27" },
    { position: 29, name: "Devil Vortex", video: "rSMoWAZOun0", creator: "Rustam", link: "https://pointercrate.com/demonlist/28" },
    { position: 30, name: "Necromancer", video: "5_-yMZIrhSk", creator: "TGI", link: "https://pointercrate.com/demonlist/29" },
    { position: 31, name: "WOW", video: "CbUVw7p0Ebg", creator: "TrusTa", link: "https://pointercrate.com/demonlist/30" },
    { position: 32, name: "ZAPHKIEL", video: "pqqznxrMs5o", creator: "Darwin", link: "https://pointercrate.com/demonlist/31" },
    { position: 33, name: "xo", video: "vcAdWah55Z4", creator: "KrmaL", link: "https://pointercrate.com/demonlist/32" },
    { position: 34, name: "Dark Flare", video: "Pb8GVDjiiQQ", creator: "KeiAs", link: "https://pointercrate.com/demonlist/33" },
    { position: 35, name: "Celestial Force", video: "ydQI1-5R6ig", creator: "MindCap", link: "https://pointercrate.com/demonlist/34" },
    { position: 36, name: "Omega", video: "rkEXUOybDXg", creator: "MindCap", link: "https://pointercrate.com/demonlist/35" },
    { position: 37, name: "Step To Hell", video: "mQ7zvkT99Qc", creator: "LaZye", link: "https://pointercrate.com/demonlist/36" },
    { position: 38, name: "Digital Descent", video: "mX8j8jG-Um8", creator: "ViPriN", link: "https://pointercrate.com/demonlist/37" },
    { position: 39, name: "Sunset Sandstorm", video: "5ary4apA0WA", creator: "crohn44", link: "https://pointercrate.com/demonlist/38" },
    { position: 40, name: "Tapwreck", video: "w5qI2iukPzI", creator: "MrLorenzo", link: "https://pointercrate.com/demonlist/39" },
    { position: 41, name: "Freedom08", video: "b1DE6OTFS4U", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/40" },
    { position: 42, name: "Cadrega City", video: "cHEGAqOgddA", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/41" },
    { position: 43, name: "Stalemate Redux", video: "t9XP1lhMrPo", creator: "TehTactiq", link: "https://pointercrate.com/demonlist/42" },
    { position: 44, name: "Auditory Breaker", video: "ZcQ5NrKmpT0", creator: "LazerBlitz", link: "https://pointercrate.com/demonlist/43" },
    { position: 45, name: "Factory Realm X", video: "bkreo_jag3E", creator: "HelpegasuS", link: "https://pointercrate.com/demonlist/44" },
    { position: 46, name: "Dolos", video: "_nCfS3ALMmk", creator: "Enzeux", link: "https://pointercrate.com/demonlist/45" },
    { position: 47, name: "Demonicat", video: "2OgX7-eqeS8", creator: "f3lixsram", link: "https://pointercrate.com/demonlist/46" },
    { position: 48, name: "Paroxysm", video: "JVlHUROeEnc", creator: "Lemons", link: "https://pointercrate.com/demonlist/47" },
    { position: 49, name: "Killbot", video: "UQvPvOGYdpw", creator: "BoldStep", link: "https://pointercrate.com/demonlist/48" },
    { position: 50, name: "Catalyze", video: "hF-TVX8wakc", creator: "ZephiroX", link: "https://pointercrate.com/demonlist/49" },
    { position: 51, name: "Photovoltaic II", video: "Kc1V9lInj3E", creator: "Mazl", link: "https://pointercrate.com/demonlist/50" },
    { position: 52, name: "Tempered Steel", video: "P9Thg6LuIlU", creator: "ItsHybrid", link: "https://pointercrate.com/demonlist/51" },
    { position: 53, name: "Delta Interface", video: "UxKZ71AuO3w", creator: "Platnuu", link: "https://pointercrate.com/demonlist/52" },
    { position: 54, name: "Ziroikapi", video: "BopdvP_-7wI", creator: "Kapinapi", link: "https://pointercrate.com/demonlist/53" },
    { position: 55, name: "Furious Flames", video: "ybtlTy2Z7d8", creator: "Eggnog", link: "https://pointercrate.com/demonlist/54" },
    { position: 56, name: "Artificial Ascent", video: "laok-nI3-t8", creator: "ViPriN", link: "https://pointercrate.com/demonlist/55" },
    { position: 57, name: "Fabrication", video: "iQhnNchayAk", creator: "KeiAs", link: "https://pointercrate.com/demonlist/56" },
    { position: 58, name: "Missing Benefits", video: "qhXKRb6afgA", creator: "TGI", link: "https://pointercrate.com/demonlist/57" },
    { position: 59, name: "BBBBBBBBBBBBBBBBBBBB", video: "SHnySmos_AE", creator: "RoiMousti", link: "https://pointercrate.com/demonlist/58" },
    { position: 60, name: "Ziroikabi", video: "UNbvNgWVu2k", creator: "RoiMousti", link: "https://pointercrate.com/demonlist/59" },
    { position: 61, name: "Ethereal Artifice", video: "RKbKYcS9aCU", creator: "Zeroya", link: "https://pointercrate.com/demonlist/60" },
    { position: 62, name: "Quantum Processing", video: "lt8GNUsFMQo", creator: "Riot", link: "https://pointercrate.com/demonlist/61" },
    { position: 63, name: "Glowy", video: "XkDcrHZS5QA", creator: "RobBuck", link: "https://pointercrate.com/demonlist/62" },
    { position: 64, name: "Cadrega Mode", video: "qcOtiV2w0UE", creator: "TCTeam", link: "https://pointercrate.com/demonlist/63" },
    { position: 65, name: "Rate Demon", video: "3rKI-n69bzY", creator: "RoiMousti", link: "https://pointercrate.com/demonlist/64" },
    { position: 66, name: "Void Wave", video: "A1mue60G4mM", creator: "CherryBT", link: "https://pointercrate.com/demonlist/65" },
    { position: 67, name: "Bausha Vortex", video: "J4Jwp3-ub3I", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/66" },
    { position: 68, name: "Balengu Vortex", video: "2BwK_ngpdPA", creator: "Temp", link: "https://pointercrate.com/demonlist/67" },
    { position: 69, name: "The Hell Field", video: "rm2dGOchJk4", creator: "Stormfly", link: "https://pointercrate.com/demonlist/68" },
    { position: 70, name: "Black Blizzard", video: "lsT5TjQ1Ubc", creator: "KrmaL", link: "https://pointercrate.com/demonlist/69" },
    { position: 71, name: "Hatred", video: "mq5-I5UXZrQ", creator: "AZuLer4", link: "https://pointercrate.com/demonlist/70" },
    { position: 72, name: "Belloq", video: "-7e3lRUBme8", creator: "Sminx", link: "https://pointercrate.com/demonlist/71" },
    { position: 73, name: "BuTiTi III", video: "uOCLYZdvSxo", creator: "JonathanGD", link: "https://pointercrate.com/demonlist/72" },
    { position: 74, name: "Audio Expulsion", video: "AZy1moiM6j0", creator: "GoodSmile", link: "https://pointercrate.com/demonlist/73" },
    { position: 75, name: "Astral Divinity", video: "vEzYofL2wuQ", creator: "knobbelboy", link: "https://pointercrate.com/demonlist/74" },
    { position: 76, name: "SINGULARITY", video: "Qhaq7XBRrZQ", creator: "Bianox", link: "https://pointercrate.com/demonlist/75" },
    { position: 77, name: "Subsonic", video: "F-AfSPnjIcM", creator: "ViPriN", link: "https://pointercrate.com/demonlist/76" },
    { position: 78, name: "Anoxysm", video: "LSQb2MQFxGo", creator: "Lemons", link: "https://pointercrate.com/demonlist/77" },
    { position: 79, name: "Infernal Abyss", video: "mgefA4FTEXk", creator: "swithi", link: "https://pointercrate.com/demonlist/78" },
    { position: 80, name: "Shock Therapy", video: "tGTieEg81Xg", creator: "Arb71703", link: "https://pointercrate.com/demonlist/79" },
    { position: 81, name: "The Hell Zone", video: "6ebIqtnGpdo", creator: "Stormfly", link: "https://pointercrate.com/demonlist/80" },
    { position: 82, name: "distraught", video: "JglmGHn-RUI", creator: "alkali", link: "https://pointercrate.com/demonlist/81" },
    { position: 83, name: "Bass Cave", video: "xp1JeqV0K5g", creator: "Bloodshot", link: "https://pointercrate.com/demonlist/82" },
    { position: 84, name: "SPEEDRUN", video: "bZJ-Qc-usrc", creator: "Kaito", link: "https://pointercrate.com/demonlist/83" },
    { position: 85, name: "Athanatos by Exenity", video: null, creator: "", link: "https://pointercrate.com/demonlist/84" },
    { position: 86, name: "Breakout Redux", video: "05f7fa5Myqk", creator: "Waivve", link: "https://pointercrate.com/demonlist/85" },
    { position: 87, name: "Ithacropolis", video: "zqRLjGI_p9I", creator: "BIGMAC77", link: "https://pointercrate.com/demonlist/86" },
    { position: 88, name: "The Hell World", video: "WEJR4EO8DzM", creator: "Stormfly", link: "https://pointercrate.com/demonlist/87" },
    { position: 89, name: "TeaM Z", video: "zu21_854jXg", creator: "99Percent", link: "https://pointercrate.com/demonlist/88" },
    { position: 90, name: "MadMansion", video: "HWIQIGy-4eI", creator: "GunnerBones", link: "https://pointercrate.com/demonlist/89" },
    { position: 91, name: "Surge of Memories", video: "9Ng5Vsbqbzo", creator: "TMNGaming", link: "https://pointercrate.com/demonlist/90" },
    { position: 92, name: "Mystic", video: "VPcjyLMgE9g", creator: "Endlevel", link: "https://pointercrate.com/demonlist/91" },
    { position: 93, name: "The Hell Origin", video: "2fZ_4jAGsQc", creator: "Stormfly", link: "https://pointercrate.com/demonlist/92" },
    { position: 94, name: "EnvY", video: "IUJdtXaUhGM", creator: "DanZmeN", link: "https://pointercrate.com/demonlist/93" },
    { position: 95, name: "Arctic Arena", video: "9DTNTVpRNUA", creator: "Eclipsed", link: "https://pointercrate.com/demonlist/94" },
    { position: 96, name: "Asmodeus", video: "3OwKOI4yXLQ", creator: "Vexion", link: "https://pointercrate.com/demonlist/95" },
    { position: 97, name: "Carnage Mode", video: "GuJkgwNJ0UU", creator: "Findexi", link: "https://pointercrate.com/demonlist/96" },
    { position: 98, name: "VendetTa", video: "HyG7HP_CDwE", creator: "CFteamgd", link: "https://pointercrate.com/demonlist/97" },
    { position: 99, name: "Dimension Breaker", video: "fIxFGfjCmA8", creator: "Bianox", link: "https://pointercrate.com/demonlist/98" },
    { position: 100, name: "Phobos", video: "wC8VJ4B2WRg", creator: "KrmaL", link: "https://pointercrate.com/demonlist/99" },
    { position: 101, name: "Super Probably Level", video: "FkFU7JHyO5g", creator: "alkali", link: "https://pointercrate.com/demonlist/100" },
    { position: 102, name: "Low Death", video: "79wQenmbG3Q", creator: "KrmaL", link: "https://pointercrate.com/demonlist/101" },
    { position: 103, name: "Sakupen Hell", video: "svyOjwLCErg", creator: "TrusTa", link: "https://pointercrate.com/demonlist/102" },
    { position: 104, name: "Extinction", video: "AfoLhYbBaVs", creator: "Cum", link: "https://pointercrate.com/demonlist/103" },
    { position: 105, name: "Ancestral Calamity", video: "L2cyjYUYeXM", creator: "MrSpaghetti", link: "https://pointercrate.com/demonlist/104" },
    { position: 106, name: "Silentium Gradas", video: "pu4m4mpRlhI", creator: "Stormfly", link: "https://pointercrate.com/demonlist/105" },
    { position: 107, name: "Blade of Justice", video: "ZWYUjgmko-A", creator: "Manix648", link: "https://pointercrate.com/demonlist/106" },
    { position: 108, name: "Betrayal of Fate by weoweoteo", video: null, creator: "", link: "https://pointercrate.com/demonlist/107" },
    { position: 109, name: "Artifice", video: "AuAdGf4yeYY", creator: "f3lixsram", link: "https://pointercrate.com/demonlist/108" },
    { position: 110, name: "Esencia", video: "xr__MN_5k5Q", creator: "Zafkiel", link: "https://pointercrate.com/demonlist/109" },
    { position: 111, name: "ATMarbl", video: "PanlasFe7ow", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/110" },
    { position: 112, name: "Epsilon", video: "LDVNlSVh2rw", creator: "Team Proxima", link: "https://pointercrate.com/demonlist/111" },
    { position: 113, name: "Atmosphere", video: "yV8jA9yU-JM", creator: "VoidSquad", link: "https://pointercrate.com/demonlist/112" },
    { position: 114, name: "Bloodbath", video: "GJ2ni0Ur1jQ", creator: "Riot", link: "https://pointercrate.com/demonlist/113" },
    { position: 115, name: "Down Bass by Spectra", video: null, creator: "", link: "https://pointercrate.com/demonlist/114" },
    { position: 116, name: "ElectroLux", video: "PS6Jg3peUbo", creator: "GuitarHeroStyles", link: "https://pointercrate.com/demonlist/115" },
    { position: 117, name: "Under lavaland", video: "jHnz395AMao", creator: "N R G", link: "https://pointercrate.com/demonlist/116" },
    { position: 118, name: "Conical Depression", video: "wdEuFpV9CXw", creator: "KrmaL", link: "https://pointercrate.com/demonlist/117" },
    { position: 119, name: "Idols", video: "EsKfImKvaFc", creator: "Zafkiel", link: "https://pointercrate.com/demonlist/118" },
    { position: 120, name: "Aurora", video: "vbsiPTq2JSw", creator: "TheKris", link: "https://pointercrate.com/demonlist/119" },
    { position: 121, name: "The Hell Bird", video: "756VHR2Tn7Y", creator: "Havok", link: "https://pointercrate.com/demonlist/120" },
    { position: 122, name: "Prismatic Haze", video: "RS5ZFcuaw3I", creator: "Cirtrax", link: "https://pointercrate.com/demonlist/121" },
    { position: 123, name: "Annihilation Nation", video: "6WiRsUbg2MQ", creator: "Zylenox", link: "https://pointercrate.com/demonlist/122" },
    { position: 124, name: "Artificial Ideology", video: "WRfaroi9PpA", creator: "TeamN2", link: "https://pointercrate.com/demonlist/123" },
    { position: 125, name: "A Bizarre Phantasm", video: "iT5Lp6vEF30", creator: "TeamN2", link: "https://pointercrate.com/demonlist/124" },
    { position: 126, name: "The Hell Factory", video: "MxzBAnBeZCE", creator: "TeamN2", link: "https://pointercrate.com/demonlist/125" },
    { position: 127, name: "Just DANCE", video: "FZBB1QgDE-Y", creator: "Texic", link: "https://pointercrate.com/demonlist/126" },
    { position: 128, name: "WaveBreaker", video: "Uky3BixaaDc", creator: "Lemons", link: "https://pointercrate.com/demonlist/127" },
    { position: 129, name: "Penultimate Phase", video: "J2NNb0iddYM", creator: "nwolc", link: "https://pointercrate.com/demonlist/128" },
    { position: 130, name: "Aftermath", video: "nhcyfGUkCMk", creator: "Satcho", link: "https://pointercrate.com/demonlist/129" },
    { position: 131, name: "INNARDS", video: "r2BI-N6rcas", creator: "Kaito", link: "https://pointercrate.com/demonlist/130" },
    { position: 132, name: "GridLocked", video: "vKXy-gx8XQI", creator: "Eclipsed", link: "https://pointercrate.com/demonlist/131" },
    { position: 133, name: "Plasma Pulse III", video: "obz_F8jnBUU", creator: "Smokes", link: "https://pointercrate.com/demonlist/132" },
    { position: 134, name: "Novalis", video: "ecuAlcs3dIw", creator: "Gryllex", link: "https://pointercrate.com/demonlist/133" },
    { position: 135, name: "Maybe Possibly Thing", video: "u7dBdD531As", creator: "iNubble", link: "https://pointercrate.com/demonlist/134" },
    { position: 136, name: "N0", video: "G9MdcWZJk9o", creator: "Metalface221", link: "https://pointercrate.com/demonlist/135" },
    { position: 137, name: "The Hell Dignity", video: "nQuVjZ11Lyw", creator: "Stormfly", link: "https://pointercrate.com/demonlist/136" },
    { position: 138, name: "Triple Six", video: "VLt8A5E3Fz4", creator: "Zylenox", link: "https://pointercrate.com/demonlist/137" },
    { position: 139, name: "Niflheim", video: "FFAHbgkNH10", creator: "Vismuth", link: "https://pointercrate.com/demonlist/138" },
    { position: 140, name: "Panasonic", video: "yCeqAKEzlrs", creator: "GuitarHeroStyles", link: "https://pointercrate.com/demonlist/139" },
    { position: 141, name: "A2Marbl", video: "VVIwks1J9Z4", creator: "Golden", link: "https://pointercrate.com/demonlist/140" },
    { position: 142, name: "Limitless", video: "QjoMS3mpJUE", creator: "Konsi", link: "https://pointercrate.com/demonlist/141" },
    { position: 143, name: "The Antimatter", video: "ZV590RxANVM", creator: "Bianox", link: "https://pointercrate.com/demonlist/142" },
    { position: 144, name: "Marathon", video: "B_L0ahpeYV4", creator: "weoweoteo", link: "https://pointercrate.com/demonlist/143" },
    { position: 145, name: "Audio Extraction", video: "RyjPsu84PMs", creator: "GoodSmile", link: "https://pointercrate.com/demonlist/144" },
    { position: 146, name: "Elite Z Rebirth", video: "B1GKgUNT8Q0", creator: "KrmaL", link: "https://pointercrate.com/demonlist/145" },
    { position: 147, name: "Twisted Tranquility", video: "TiaOm9j36Pg", creator: "Flukester", link: "https://pointercrate.com/demonlist/146" },
    { position: 148, name: "Unearthed", video: "yvR454BuffE", creator: "YakobNugget", link: "https://pointercrate.com/demonlist/147" },
    { position: 149, name: "Breakout", video: "foEA5hS1aUw", creator: "Surv", link: "https://pointercrate.com/demonlist/148" },
    { position: 150, name: "Grill Kill", video: "kVzmcHGMcpY", creator: "RoiMousti", link: "https://pointercrate.com/demonlist/149" },
];
