import { SimplifiedDemon } from "./types";

export const veryOldDemons: SimplifiedDemon[] = [
    { position: 1, name: "Erebus", video: "8csWDx6C2YI", creator: "BoldStep", link: "https://pointercrate.com/demonlist/permalink/93/" },
    { position: 2, name: "Sonic Wave", video: "GpXTwPgweAk", creator: "Sunix", link: "https://pointercrate.com/demonlist/permalink/118/" },
    { position: 3, name: "Yatagarasu", video: "GrGFFPhtAFc", creator: "TrusTa", link: "https://pointercrate.com/demonlist/permalink/146/" },
    { position: 4, name: "ZAPHKIEL", video: "RkW_aKtshMI", creator: "Darwin", link: "https://pointercrate.com/demonlist/permalink/42/" },
    { position: 5, name: "Artificial Ascent", video: "laok-nI3-t8", creator: "ViPriN", link: "https://pointercrate.com/demonlist/permalink/47/" },
    { position: 6, name: "Bausha Vortex", video: "J4Jwp3-ub3I", creator: "Pennutoh", link: "https://pointercrate.com/demonlist/permalink/206/" },
    { position: 7, name: "Mystic", video: "VPcjyLMgE9g", creator: "Endlevel", link: "https://pointercrate.com/demonlist/permalink/171/" },
    { position: 8, name: "Devil Vortex", video: "ntCP1ao3ogI", creator: "Rustam", link: "https://pointercrate.com/demonlist/permalink/88/" },
    { position: 9, name: "Step To Hell", video: "mQ7zvkT99Qc", creator: "LaZye", link: "https://pointercrate.com/demonlist/permalink/89/" },
    { position: 10, name: "Sakupen Hell", video: "svyOjwLCErg", creator: "TrusTa", link: "https://pointercrate.com/demonlist/permalink/30/" },
    { position: 11, name: "SubSonic", video: "F-AfSPnjIcM", creator: "ViPriN", link: "https://pointercrate.com/demonlist/permalink/147/" },
    { position: 12, name: "The Hell World", video: "WEJR4EO8DzM", creator: "Stormfly", link: "https://pointercrate.com/demonlist/permalink/124/" },
    { position: 13, name: "Black Blizzard", video: "lsT5TjQ1Ubc", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/204/" },
    { position: 14, name: "Hatred", video: "mq5-I5UXZrQ", creator: "AZuLer4", link: "https://pointercrate.com/demonlist/permalink/203/" },
    { position: 15, name: "Bloodbath", video: "twTw4fjT0ik", creator: "Riot", link: "https://pointercrate.com/demonlist/permalink/69/" },
    { position: 16, name: "Phobos", video: "wC8VJ4B2WRg", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/202/" },
    { position: 17, name: "Athanatos", video: "RF8aW4Ngwbw", creator: "Exenity", link: "https://pointercrate.com/demonlist/permalink/41/" },
    { position: 18, name: "Aurora", video: "vbsiPTq2JSw", creator: "TheKris", link: "https://pointercrate.com/demonlist/permalink/36/" },
    { position: 19, name: "Infernal Abyss", video: "mgefA4FTEXk", creator: "Ggb0y", link: "https://pointercrate.com/demonlist/permalink/38/" },
    { position: 20, name: "Carnage Mode", video: "GuJkgwNJ0UU", creator: "Findexi", link: "https://pointercrate.com/demonlist/permalink/52/" },
    { position: 21, name: "Conical Depression", video: "wdEuFpV9CXw", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/35/" },
    { position: 22, name: "The Hell Zone", video: "6ebIqtnGpdo", creator: "Stormfly", link: "https://pointercrate.com/demonlist/permalink/162/" },
    { position: 23, name: "Betrayal of Fate", video: null, creator: "weoweoteo", link: "https://pointercrate.com/demonlist/permalink/197/" },
    { position: 24, name: "A Bizarre Phantasm", video: "ivC0NJVPAwo", creator: "TeamN2", link: "https://pointercrate.com/demonlist/permalink/169/" },
    { position: 25, name: "Down Bass", video: null, creator: "Spectra", link: "https://pointercrate.com/demonlist/permalink/77/" },
    { position: 26, name: "Artificial Ideology", video: "WRfaroi9PpA", creator: "TeamN2", link: "https://pointercrate.com/demonlist/permalink/33/" },
    { position: 27, name: "Blade of Justice", video: "6018CbEjA-4", creator: "Manix648", link: "https://pointercrate.com/demonlist/permalink/70/" },
    { position: 28, name: "Audio Extraction", video: "RyjPsu84PMs", creator: "GoodSmile", link: "https://pointercrate.com/demonlist/permalink/167/" },
    { position: 29, name: "Plasma Pulse III", video: "obz_F8jnBUU", creator: "Smokes", link: "https://pointercrate.com/demonlist/permalink/76/" },
    { position: 30, name: "aftermath", video: "nhcyfGUkCMk", creator: "Satcho", link: "https://pointercrate.com/demonlist/permalink/104/" },
    { position: 31, name: "Novalis", video: "ecuAlcs3dIw", creator: "Gryllex", link: "https://pointercrate.com/demonlist/permalink/121/" },
    { position: 32, name: "The Hell Dignity", video: "nQuVjZ11Lyw", creator: "Stormfly", link: "https://pointercrate.com/demonlist/permalink/212/" },
    { position: 33, name: "Breakout", video: "foEA5hS1aUw", creator: "Surv", link: "https://pointercrate.com/demonlist/permalink/138/" },
    { position: 34, name: "Twisted Tranquility", video: "TiaOm9j36Pg", creator: "Flukester", link: "https://pointercrate.com/demonlist/permalink/196/" },
    { position: 35, name: "Niflheim", video: "FFAHbgkNH10", creator: "Vismuth", link: "https://pointercrate.com/demonlist/permalink/73/" },
    { position: 36, name: "Red World Rebirth", video: "WsxDUMLRqN4", creator: "Riot", link: "https://pointercrate.com/demonlist/permalink/61/" },
    { position: 37, name: "The Flawless", video: "RHOCE37dP2A", creator: "IIIRyanIII", link: "https://pointercrate.com/demonlist/permalink/26/" },
    { position: 38, name: "The Hell Factory", video: "MxzBAnBeZCE", creator: "TeamN2", link: "https://pointercrate.com/demonlist/permalink/96/" },
    { position: 39, name: "SUBVERSIVE", video: "9sxy51MfUKU", creator: "Snowr33de", link: "https://pointercrate.com/demonlist/permalink/60/" },
    { position: 40, name: "Elite Z Rebirth", video: "B1GKgUNT8Q0", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/166/" },
    { position: 41, name: "Uprise", video: "4RhvXuFLBQc", creator: "Blad3M", link: "https://pointercrate.com/demonlist/permalink/141/" },
    { position: 42, name: "Allegiance", video: "wzutYMNXr-Y", creator: "nikroplays", link: "https://pointercrate.com/demonlist/permalink/143/" },
    { position: 43, name: "Deception Dive", video: "A6xBC52UN4M", creator: "Rustam", link: "https://pointercrate.com/demonlist/permalink/164/" },
    { position: 44, name: "Cataclysm", video: "vGV4j8C66JY", creator: "Ggb0y", link: "https://pointercrate.com/demonlist/permalink/142/" },
    { position: 45, name: "Heartbeat", video: "UDVbmaJGlKQ", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/220/" },
    { position: 46, name: "ICE Carbon Diablo X", video: null, creator: "Roadbose", link: "https://pointercrate.com/demonlist/permalink/111/" },
    { position: 47, name: "Retention", video: "3VUfd7jRt5U", creator: "WOOGI1411", link: "https://pointercrate.com/demonlist/permalink/190/" },
    { position: 48, name: "AcropoliX", video: "9GrlZLD8wZ0", creator: "SoulsTRK", link: "https://pointercrate.com/demonlist/permalink/192/" },
    { position: 49, name: "The Ultimate Phase", video: null, creator: "Andromeda", link: "https://pointercrate.com/demonlist/permalink/215/" },
    { position: 50, name: "Temple of Destiny", video: "mQzjEsBE2qY", creator: "DrakeGhast", link: "https://pointercrate.com/demonlist/permalink/14/" },
    { position: 51, name: "Photovoltaic", video: "wx0xuyw0uHg", creator: "Mazl", link: "https://pointercrate.com/demonlist/permalink/100/" },
    { position: 52, name: "Creeper Force", video: "l2Kk2re3rJo", creator: "CreeperMILK", link: "https://pointercrate.com/demonlist/permalink/176/" },
    { position: 53, name: "Asymmetry", video: "NCQv0-CIZ0M", creator: "WOOGI1411", link: "https://pointercrate.com/demonlist/permalink/225/" },
    { position: 54, name: "Catastrophic", video: null, creator: "Lalter", link: "https://pointercrate.com/demonlist/permalink/175/" },
    { position: 55, name: "Cosmic Calamity", video: "bIS_dBO56S0", creator: "SrGuillester", link: "https://pointercrate.com/demonlist/permalink/130/" },
    { position: 56, name: "Crimson Clutter", video: "3-bYZqsyZAI", creator: "RedUniverse", link: "https://pointercrate.com/demonlist/permalink/56/" },
    { position: 57, name: "Cyber Chaos", video: "S1qRt75W2BI", creator: "Hinds", link: "https://pointercrate.com/demonlist/permalink/227/" },
    { position: 58, name: "Dark RainBow Rebirth", video: "QdzguI3kK_A", creator: "knobbelboy", link: "https://pointercrate.com/demonlist/permalink/179/" },
    { position: 59, name: "Duelo Maestro", video: "_ownLb_GPRg", creator: "Nacho21", link: "https://pointercrate.com/demonlist/permalink/57/" },
    { position: 60, name: "Elements X", video: "j3ngCBs_Pi8", creator: "Eiken", link: "https://pointercrate.com/demonlist/permalink/181/" },
    { position: 61, name: "Entwined Room", video: null, creator: "MidNight", link: "https://pointercrate.com/demonlist/permalink/217/" },
    { position: 62, name: "Falling Up", video: "gHHqPIvZXeM", creator: "KrmaL", link: "https://pointercrate.com/demonlist/permalink/116/" },
    { position: 63, name: "Future Circles", video: "VlHuB_gRFzI", creator: "KeiAs", link: "https://pointercrate.com/demonlist/permalink/208/" },
    { position: 64, name: "Galatic Fragility", video: "nQvDMt5WmkQ", creator: "TeamSmokeWeed", link: "https://pointercrate.com/demonlist/permalink/17/" },
    { position: 65, name: "Galaxy Breaker", video: "6el_wN6FkBA", creator: "Bianox", link: "https://pointercrate.com/demonlist/permalink/108/" },
    { position: 66, name: "Hate War", video: "CPfmyR1oegE", creator: "Stormfly", link: "https://pointercrate.com/demonlist/permalink/98/" },
    { position: 67, name: "HyperSonic", video: "RmrPEJ7Z6lY", creator: "ViPriN", link: "https://pointercrate.com/demonlist/permalink/214/" },
    { position: 68, name: "Kurumi City", video: "UgrjdXJc3wg", creator: "xnail", link: "https://pointercrate.com/demonlist/permalink/106/" },
    { position: 69, name: "Light Years", video: "E4ejBDnz1Gg", creator: "Smokes", link: "https://pointercrate.com/demonlist/permalink/226/" },
    { position: 70, name: "Matilda the Machine", video: "_ICKNhOQ4Tw", creator: "Jeyzor", link: "https://pointercrate.com/demonlist/permalink/158/" },
    { position: 71, name: "Necropolis", video: null, creator: "NePtunE", link: "https://pointercrate.com/demonlist/permalink/103/" },
    { position: 72, name: "New Supersonic", video: "p0vz4e3cBV4", creator: "CronosCrl", link: "https://pointercrate.com/demonlist/permalink/228/" },
    { position: 73, name: "Night Terrors", video: "bPOHEFKLY_c", creator: "Hinds", link: "https://pointercrate.com/demonlist/permalink/150/" },
    { position: 74, name: "Plasma Pulse II", video: "R6rDdoqB_-A", creator: "Giron", link: "https://pointercrate.com/demonlist/permalink/188/" },
    { position: 75, name: "Quest for Perfection", video: "MAN_ZWb2rY0", creator: "LazerBlitz", link: "https://pointercrate.com/demonlist/permalink/223/" },
    { position: 76, name: "Sadism", video: "L0rDpGSJxXc", creator: "Nox", link: "https://pointercrate.com/demonlist/permalink/16/" },
    { position: 77, name: "The JanuS Miracle", video: null, creator: "Megadere", link: "https://pointercrate.com/demonlist/permalink/144/" },
    { position: 78, name: "Ultraviolet", video: "GxvVgS1mSnE", creator: "ViPriN", link: "https://pointercrate.com/demonlist/permalink/48/" },
    { position: 79, name: "Wander of Thought", video: "e1NH0e1LpBg", creator: "Noriega", link: "https://pointercrate.com/demonlist/permalink/224/" },
    { position: 80, name: "Wolfstep", video: "0LV8Nm4ndE8", creator: "RLOL", link: "https://pointercrate.com/demonlist/permalink/99/" },
    { position: 81, name: "X Adventure", video: "nO2sM_KIPmI", creator: "pasiblitz", link: "https://pointercrate.com/demonlist/permalink/15/"
    }
];
