name: Deploy to Github Pages

on:
  push:
    branches: [ vue-rewrite ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          
      - name: Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install and Build
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
