name: Deploy to Github Pages

on:
  push:
    branches: [ vue-rewrite ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          
      - name: Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install and Build
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

